# Generated by Django 3.1 on 2020-11-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_time', models.DateTimeField(verbose_name='异常检测时间')),
                ('data_a', models.TextField(verbose_name='当天180分钟数据')),
                ('data_b', models.TextField(verbose_name='一天前180分钟数据')),
                ('data_c', models.TextField(verbose_name='一周前180分钟数据')),
                ('mark_flag', models.BooleanField(default=False, verbose_name='是否标注')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'Anomaly',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_id', models.CharField(max_length=64, verbose_name='指标id')),
                ('attr_name', models.CharField(max_length=64, verbose_name='指标名称')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'Attr',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='ViewSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_id', models.CharField(max_length=64, verbose_name='指标集id')),
                ('view_name', models.CharField(max_length=64, verbose_name='指标集名称')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'ViewSet',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='TrainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='训练任务ID')),
                ('sample_num', models.IntegerField(verbose_name='样本总量')),
                ('positive_sample_num', models.IntegerField(verbose_name='正样本数量')),
                ('negative_sample_num', models.IntegerField(verbose_name='负样本数量')),
                ('window', models.IntegerField(verbose_name='时间窗口')),
                ('model_name', models.CharField(max_length=64, verbose_name='模型名称')),
                ('source', models.CharField(default='Metis', max_length=32, verbose_name='来源')),
                ('start_date', models.DateTimeField(verbose_name='开始训练时间')),
                ('end_date', models.DateTimeField(verbose_name='结束训练时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_train_task', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'TrainTask',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='SampleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Metis', max_length=32, verbose_name='来源')),
                ('train_or_test', models.CharField(blank=True, max_length=32, null=True, verbose_name='训练集OR测试集')),
                ('positive_or_negative', models.CharField(blank=True, max_length=32, null=True, verbose_name='正样本OR负样本')),
                ('window', models.IntegerField(verbose_name='时间窗口')),
                ('anomaly_time', models.DateTimeField(verbose_name='异常检测时间')),
                ('data_a', models.TextField(verbose_name='当天180分钟数据')),
                ('data_b', models.TextField(verbose_name='一天前360分钟数据')),
                ('data_c', models.TextField(verbose_name='一周前360分钟数据')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_sample_set', to='MetisModels.anomaly', verbose_name='关联异常')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_sample_set', to='MetisModels.attr', verbose_name='指标')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_sample_set', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'SampleSet',
                'ordering': ('-update_date',),
            },
        ),
        migrations.AddField(
            model_name='attr',
            name='view_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_attr', to='MetisModels.viewset', verbose_name='指标集'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_anomaly', to='MetisModels.attr', verbose_name='指标'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_anomaly', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
