# Generated by Django 3.1 on 2020-11-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetisModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traintask',
            name='task_status',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='任务状态'),
        ),
    ]
