# Generated by Django 3.0.5 on 2020-12-22 14:31

import MetisModels.sample_set_upload_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MetisModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSetUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_set_upload_id', models.CharField(max_length=255, unique=True, verbose_name='上传任务ID')),
                ('sample_count', models.IntegerField(default=0, verbose_name='样本数量')),
                ('file_name', models.CharField(max_length=255, verbose_name='上传文件名')),
                ('file_path', models.FileField(upload_to=MetisModels.sample_set_upload_models.upload_to)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_sample_set_upload', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'db_table': 'SampleSetUpload',
                'ordering': ('-update_date',),
            },
        ),
        migrations.AddField(
            model_name='sampleset',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_sample_set', to='MetisModels.SampleSetUpload', verbose_name='关联上传'),
        ),
    ]
