# Generated by Django 3.1 on 2020-12-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetisModels', '0002_traintask_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='mark_flag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='标注正负样本'),
        ),
    ]
